name: Test Workflow

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Print message
      run: echo "GitHub Actions is working!"
      
    - name: List files
      run: ls -la
      
    - name: Show current date
      run: date